[features]
seeds = false
skip-lint = false
[programs.localnet]
social = "AfjULZsRAw3TDX2m5pdMe27TpWNU33VWVKDCgDn5MvTA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/sohamjog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
